on:
    push:
        branches:
            - master
            - main
    pull_request:
name: Tests
jobs:
    Tests:
        name: Tests
        strategy:
            matrix:
                go-version:
                    - 1.18.x
                    - 1.19.x
                platform:
                    - ubuntu-latest
                    - windows-latest
        runs-on: '${{ matrix.platform }}'
        steps:
            -   name: Install Go
                uses: actions/setup-go@v4
                with:
                    go-version: '${{ matrix.go-version }}'
            -   name: Setup Golang caches
                uses: actions/cache@v3
                with:
                    # In order:
                    # * Module download cache
                    # * Build cache (Linux)
                    # * Build cache (Mac)
                    # * Build cache (Windows)
                    path: |
                        ~/go/pkg/mod
                        ~/.cache/go-build
                        ~/Library/Caches/go-build
                        ~\AppData\Local\go-build
                    key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
                    restore-keys: |
                        ${{ runner.os }}-go-${{ matrix.go-version }}-
            -   name: Fetch Repository
                uses: actions/checkout@v3
            -   name: Test PASETO Middleware
                run: cd ./paseto && go test ./... -v -race
            -   name: Test Fiberzap Middleware
                run: cd ./fiberzap && go test ./... -v -race
            -   name: Test otelfiber Middleware
                run: cd ./otelfiber && go test ./... -v -race
            -   name: Test swagger Middleware
                run: cd ./swagger && go test ./... -v -race
            -   name: Test casbin Middleware
                run: cd ./casbin && go test ./... -v -race
            -   name: Test fibernewrelic Middleware
                run: cd ./fibernewrelic && go test ./... -v -race
            -   name: Test opafiber Middleware
                run: cd ./opafiber && go test ./... -v -race
            -   name: Test fiberi18n Middleware
                run: cd ./fiberi18n && go test ./... -v -race
            -   name: Test fiberzerolog Middleware
                run: cd ./fiberzerolog && go test ./... -v -race
            -   name: Test minify Middleware
                run: cd ./minify && go test ./... -v race
